INSERT INTO car (category, brand, model, year, color, rent_price_day, seats, image, is_automatic) VALUES
                                                                                                  ('SUV', 'Toyota', 'Rav4', 2021, 'Red', 50, 5, 'assets/images/cars/c1.png', TRUE),
                                                                                                  ('Sedan', 'Honda', 'Accord', 2019, 'Blue', 40, 4, 'assets/images/cars/c2.png', TRUE),
                                                                                                  ('Sports', 'Ferrari', 'F8', 2020, 'Yellow', 200, 2, 'assets/images/cars/c3.png', TRUE),
                                                                                                  ('Hatchback', 'Ford', 'Focus', 2018, 'Green', 30, 4, 'assets/images/cars/c4.png', FALSE),
                                                                                                  ('Convertible', 'BMW', 'Z4', 2022, 'Black', 70, 2, 'assets/images/cars/c5.png', TRUE),
                                                                                                  ('Truck', 'Chevrolet', 'Silverado', 2021, 'White', 60, 6, 'assets/images/cars/c6.png', TRUE),
                                                                                                  ('Minivan', 'Chrysler', 'Pacifica', 2019, 'Silver', 55, 7, 'assets/images/cars/c7.png', TRUE),
                                                                                                  ('Coupe', 'Audi', 'A5', 2020, 'Grey', 65, 4, 'assets/images/cars/c8.png', TRUE),
                                                                                                  ('Crossover', 'Hyundai', 'Tucson', 2021, 'Orange', 45, 5, 'assets/images/cars/c9.png', TRUE),
                                                                                                  ('Luxury', 'Mercedes', 'S-Class', 2022, 'Purple', 100, 4, 'assets/images/cars/c10.png', TRUE),
                                                                                                  ('SUV', 'Toyota', 'Highlander', 2022, 'Black', 60, 5, 'assets/images/cars/c11.png', TRUE),
                                                                                                  ('Sedan', 'Toyota', 'Corolla', 2020, 'White', 45, 4, 'assets/images/cars/c12.png', TRUE),
                                                                                                  ('Sports', 'Porsche', '911', 2021, 'Red', 210, 2, 'assets/images/cars/c13.png', TRUE),
                                                                                                  ('Hatchback', 'Volkswagen', 'Golf', 2019, 'Blue', 35, 4, 'assets/images/cars/c14.png', FALSE),
                                                                                                  ('Convertible', 'Mercedes', 'SLK', 2022, 'Red', 80, 2, 'assets/images/cars/c15.png', TRUE),
                                                                                                  ('Truck', 'Ford', 'F-150', 2021, 'Grey', 65, 6, 'assets/images/cars/c16.png', TRUE),
                                                                                                  ('Minivan', 'Toyota', 'Sienna', 2020, 'Silver', 50, 7, 'assets/images/cars/c17.png', TRUE),
                                                                                                  ('Coupe', 'BMW', '4 Series', 2021, 'Blue', 75, 4, 'assets/images/cars/c18.png', TRUE),
                                                                                                  ('Crossover', 'Nissan', 'Rogue', 2022, 'Black', 50, 5, 'assets/images/cars/c19.png', TRUE),
                                                                                                  ('Luxury', 'Audi', 'A8', 2021, 'White', 110, 4, 'assets/images/cars/c20.png', TRUE);
